

using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace PA.Core.Models
{
	public class Employee
	{

		//  PK is provided by the application rather than generated by the database.
		[DatabaseGenerated(DatabaseGeneratedOption.None)]
		[Required]
		public Guid Id { get; set; }

		public DateTime? JoinDate { get; set; } = DateTime.Now;

		[Required]
		[StringLength(30)]
		[PersonalData]
		public string FirstName { get; set; } = string.Empty;

		[Required]
		[StringLength(30)]
		[PersonalData]
		public string LasttName { get; set; } = string.Empty;

		[StringLength(8)]
		[PersonalData]
		public string? Initials { get; set; } = string.Empty;

		[Required]
		[StringLength(24)]
		public string UserName { get; set; } = string.Empty;

		[Required]
		public PrimaryDepartment PrimaryDepartment { get; set; } = PrimaryDepartment.GENERAL_SERVICE;

		[Required]
		[StringLength(5)]
		public string Title { get; set; } = string.Empty;

		[StringLength(256)]
		[PersonalData]
		public string? Photo { get; set; } = string.Empty;
		[DataType(DataType.EmailAddress)]
		[Required]
		public string Email { get; set; } = string.Empty;
	}
}
